/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import java.util.ArrayList;

/**
 *
 * @author Igor Ribeiro
 */
public class index extends javax.swing.JFrame {

    /** Creates new form index */
    public index() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        raiz = new javax.swing.JTextField();
        verifica = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resposta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Insira o número cuja a raíz descobriremos:");

        verifica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raíz quadrada", "Raíz cúbica" }));

        jLabel2.setText("Processo:");

        Resposta.setColumns(20);
        Resposta.setRows(5);
        jScrollPane1.setViewportView(Resposta);

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(raiz, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(verifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String entrada = null;
        entrada = raiz.getText();
        ArrayList Raiz = new ArrayList();
        char[] letra = entrada.toCharArray();
        int tamanho = letra.length;
        int i =0;
        for(i=0; i<tamanho; i++){
            Raiz.add(letra[i]);
        }
        int c = Integer.parseInt(raiz.getText());
        double d = Math.sqrt(c);
        double f= d;
        int e = (int) d;
        if(e*e == c){
        
        
        String Teste = verifica.getSelectedItem().toString();
        
        if(Teste.equals("Raíz quadrada")){
        //System.out.println("é raiz quadrada mesmo mano");
        int o = Raiz.size() - 1;
        //System.out.println("1 " + Raiz.get(o));
        
        if(tamanho < 3){
            double a = Integer.parseInt(raiz.getText());
            a = Math.sqrt(a);
            Resposta.setText("Para total aproveitamento deste método, utilize números com\ntrês ou mais dígitos\n Resposta: " + a);
        }
        
        if(tamanho == 3){
            String a = Raiz.get(0).toString();
            int primeiro = Integer.parseInt(a);
            a = Raiz.get(1).toString();
            int segundo = Integer.parseInt(a);
             a = Raiz.get(2).toString();
            int terceiro = Integer.parseInt(a);
            //System.out.println("1 " + primeiro);
            //System.out.println("2 " + segundo);
            //System.out.println("3 " + terceiro);

            String mask = "";
            mask+= "Primeiro você elimina o número (no nosso caso, o " + segundo + ")\n";
            mask+= "Então, você verifica se o último número é 6 ou 5, se for, você repete ele e então completa pra 10,"
                    + "se não, apenas colocaremos a raíz quadrada mais próxima dele (sem ultrapassar)\n";
            
            
            if(terceiro == 6 || terceiro == 5){
                int k = 10 - terceiro;
                
                mask+= "Como no nosso caso é, vamos fazer assim:\n" + terceiro + "\n" + k + "\n\n";
                
                if(primeiro == 1 || primeiro == 2 || primeiro == 3){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 1, então\n repetimos o 1 antes de ambos os números, assim:\n";
                    mask+="1 " + terceiro + "\n1 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 1 * 2, onde ficaremos com '2')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(primeiro < 2){
                    mask+= "como 1 é menor que 2, vamos ficar com o menor número (1" + k +")";
                    mask+= "\n\n Resposta = 1"+k ;
                    Resposta.setText(mask);}
                    if(primeiro >=2){
                        mask+= "como "+primeiro+" é maior ou igual a 2, vamos ficar com o maior número (1" + terceiro +")";
                    mask+= "\n\n Resposta = 1"+terceiro ;
                    Resposta.setText(mask);
                    }
                    }
                
                if(primeiro== 4 || primeiro == 5 || primeiro == 6 || primeiro == 7 || primeiro == 8){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 2, então\n repetimos o 2 antes de ambos os números, assim:\n";
                    mask+="2 " + terceiro + "\n2 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 2 * 3, onde ficaremos com '6')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(primeiro < 6){
                    mask+= "como "+primeiro+" é menor que 6, vamos ficar com o menor número (2" + k +")";
                    mask+= "\n\n Resposta = 2"+k ;
                    Resposta.setText(mask);
                    }if(primeiro >= 6){
                    mask+= "como "+primeiro+" é maior ou igual a6, vamos ficar com o maior número (2" + terceiro +")";
                    mask+= "\n\n Resposta = 2"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (primeiro == 9){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                    mask+="3 " + terceiro + "\n3 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    mask+= "como 9 é menor que 12, vamos ficar com o menor número (3" + k +")";
                    mask+= "\n\n Resposta = 3"+k ;
                    Resposta.setText(mask);
                }
                
            }if(terceiro != 5 && terceiro != 6){
                mask+= "como não é, vamos achar a exata mais próxima dele para aí então completarmos para 10, que no caso é:";
                if(c == 100){
                    Resposta.setText("Oras, a do 100 é bem fácil, é óbvio que é 10 :p");
                }
                if(c == 400){
                    Resposta.setText("Oras, a do 400 é bem fácil, é óbvio que é 20 :p");
                }
                if(c == 900){
                    Resposta.setText("Oras, a do 900 é bem fácil, é óbvio que é 30 :p");
                }
                
                
                if(terceiro == 1 || terceiro == 2 || terceiro == 3){
                    mask+= "1, e para completarmos para dez: 9, então deixemos assim: \n1\n9";
                    if(primeiro== 9){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                        mask+="3 1" + "\n3 9";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        mask+= "como 9 é menor que 12, vamos ficar com o menor número (3 1)";
                        mask+= "\n\n Resposta = 31" ;
                    Resposta.setText(mask);
                    }
                    
                    if(primeiro== 4 || primeiro == 5 || primeiro == 6 || primeiro == 7 || primeiro == 8){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 2, então\n repetimos o 2 antes de ambos os números, assim:\n";
                        mask+="2 1" + "\n2 9";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 2 * 3, onde ficaremos com '6')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        if(primeiro < 6){
                        mask+= "como "+primeiro+" é menor que 6, vamos ficar com o menor número (2 1)";
                        mask+= "\n\n Resposta = 21" ;
                    Resposta.setText(mask);}
                        if(primeiro >= 6){
                        mask+= "como "+primeiro+" é maior ou igual que 6, vamos ficar com o maior número (2 9)";
                        mask+= "\n\n Resposta = 29" ;
                    Resposta.setText(mask);
                        }
                    }
                    
                    if(primeiro== 1 || primeiro == 2 || primeiro == 3 ){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 1, então\n repetimos o 1 antes de ambos os números, assim:\n";
                        mask+="1 1" + "\n1 9";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 1 * 2, onde ficaremos com '2')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        if(primeiro < 2){
                        mask+= "como "+primeiro+" é menor que 2, vamos ficar com o menor número (1 1)";
                        mask+= "\n\n Resposta = 11" ;
                    Resposta.setText(mask);}
                        if(primeiro >=2){
                        mask+= "como "+primeiro+" é maior ou igual que 2, vamos ficar com o maior número (1 9)";
                        mask+= "\n\n Resposta = 19" ;
                    Resposta.setText(mask);
                        }
                    }
                }
                
                if(terceiro > 3 && terceiro <9){
                    mask+= "2, e para completarmos para dez: 8, então deixemos assim: \n2\n8";
                           if(primeiro== 9){
                            mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                            mask+="3 2" + "\n3 8";
                            mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                                + " número e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                                + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                            mask+= "como 3 é menor que 12, vamos ficar com o menor número (3 2)";
                            mask+= "\n\n Resposta = 32" ;
                            Resposta.setText(mask);
                        }
                    
                    if(primeiro== 4 || primeiro == 5 || primeiro == 6 || primeiro == 7 || primeiro == 8){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 2, então\n repetimos o 2 antes de ambos os números, assim:\n";
                        mask+="2 2" + "\n2 8";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 2 * 3, onde ficaremos com '6')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                            if(primeiro > 5){
                            mask+= "como "+primeiro+" é maior ou igual a 6, vamos ficar com o maior número (2 8)";
                            mask+= "\n\n Resposta = 28" ;
                            Resposta.setText(mask);
                            }   
                            
                            if(primeiro < 6){
                            mask+= "como "+primeiro+" é menor que 6, vamos ficar com o menor número (2 2)";
                            mask+= "\n\n Resposta = 22" ;
                            Resposta.setText(mask);}
                            }
                    
                    if(primeiro== 1 || primeiro == 2 || primeiro == 3 ){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 1, então\n repetimos o 1 antes de ambos os números, assim:\n";
                        mask+="1 2" + "\n1 8";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 1 * 2, onde ficaremos com '2')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        if(primeiro < 2){
                        mask+= "como "+primeiro+" é menor que 2, vamos ficar com o menor número (1 2)";
                        mask+= "\n\n Resposta = 12" ;
                    Resposta.setText(mask);
                    }if(primeiro > 2){
                         mask+= "como "+primeiro+" é maior ou iguala que 2, vamos ficar com o menor número (1 8)";
                        mask+= "\n\n Resposta = 18" ;
                    Resposta.setText(mask);
                    }}
                    
                
                }
                
                if(terceiro == 9){
                    mask+= "3, e para completarmos para dez: 7, então deixemos assim: \n1\n9\n";
                    if(primeiro== 9){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                        mask+="3 1" + "\n3 9";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        mask+= "como 9 é menor que 12, vamos ficar com o menor número (3 1)";
                        mask+= "\n\n Resposta = 31" ;
                    Resposta.setText(mask);
                    }
                    
                    if(primeiro== 4 || primeiro == 5 || primeiro == 6 || primeiro == 7 || primeiro == 8){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 2, então\n repetimos o 2 antes de ambos os números, assim:\n";
                        mask+="2 3" + "\n2 7";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 2 * 3, onde ficaremos com '6')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        if(primeiro < 6){
                        mask+= "como "+primeiro+" é menor que 6, vamos ficar com o menor número (2 3)";
                        mask+= "\n\n Resposta = 23" ;
                    Resposta.setText(mask);}
                        if(primeiro >= 6){
                        mask+= "como "+primeiro+" é maior ou igual que 6, vamos ficar com o maior número (2 7)";
                        mask+= "\n\n Resposta = 27" ;
                    Resposta.setText(mask);
                        }
                    }
                    
                    if(primeiro== 1 || primeiro == 2 || primeiro == 3 ){
                        mask+="Agora vamos, ver a raíz exata mais perto do primeiro número, que no nosso \ncaso é 1, então\n repetimos o 1 antes de ambos os números, assim:\n";
                        mask+="1 3" + "\n1 7";
                        mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o primeiro"
                            + " número e multiplicar pelo seu sucessor \n(no nosso caso, 1 * 2, onde ficaremos com '2')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                        if(primeiro < 2){
                        mask+= "como "+primeiro+" é menor que 2, vamos ficar com o menor número (1 3)";
                        mask+= "\n\n Resposta = 13" ;
                    Resposta.setText(mask);}
                        if(primeiro >=2){
                        mask+= "como "+primeiro+" é maior ou igual que 2, vamos ficar com o maior número (1 7)";
                        mask+= "\n\n Resposta = 17" ;
                    Resposta.setText(mask);
                        }
                    }
                }
                
                
                
                
            }
        }
        
        if(tamanho ==4){
            String a = Raiz.get(0).toString();
            int primeiro = Integer.parseInt(a);
            a = Raiz.get(1).toString();
            int segundo = Integer.parseInt(a);
             a = Raiz.get(2).toString();
            int quarto = Integer.parseInt(a);
            a= Raiz.get(3).toString();
            int terceiro= Integer.parseInt(a);
            System.out.println("terceiro: " + terceiro + "\nquarto: " +quarto);
            String teste = "" +primeiro + segundo;
            int n;
            n = Integer.parseInt(teste);
            String mask = "";
            mask+= "Primeiro você elimina o penúltimo número (no nosso caso, o " + quarto + ")\n";
            mask+= "Então, você verifica se o último número é 6 ou 5, se for, você repete ele e então completa pra 10,"
                    + "se não, apenas colocaremos a raíz quadrada mais próxima dele (sem ultrapassar)\n";
            
            if(terceiro == 6 || terceiro == 5){
                int k = 10 - terceiro;
                System.out.println("muuuito puto" + terceiro);
                mask+= "Como no nosso caso é, vamos fazer assim:\n" + terceiro + "\n" + k + "\n\n";
                
                if(n >= 10 && n < 16){
                    mask+="Agora vamos, ver a raíz exata mais perto dos dpos primeiros números ("+n+"), que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                    mask+="3 " + terceiro + "\n3 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o a raiz achada"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 12){
                    mask+= "como "+n+" é menor que 12, vamos ficar com o menor número (3" + k +")";
                    mask+= "\n\n Resposta = 3"+k ;
                    Resposta.setText(mask);}
                    if(n >=12){
                        mask+= "como "+n+" é maior ou igual a 12, vamos ficar com o maior número (3" + terceiro +")";
                    mask+= "\n\n Resposta = 3"+terceiro ;
                    Resposta.setText(mask);

                    }
                    }
                
                if(n >= 16 && n < 25){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 4, então\n repetimos o 4 antes de ambos os números, assim:\n";
                    mask+="4 " + terceiro + "\n4 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 4 * 5, onde ficaremos com '20')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 20){
                    mask+= "como "+n+" é menor que 20, vamos ficar com o menor número (4" + k +")";
                    mask+= "\n\n Resposta = 2"+k ;
                    Resposta.setText(mask);
                    }if(n >= 20){
                    mask+= "como "+n+" é maior ou igual a 20, vamos ficar com o maior número (4" + terceiro +")";
                    mask+= "\n\n Resposta = 4"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 25 && n < 36){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 5, então\n repetimos o 5 antes de ambos os números, assim:\n";
                    mask+="5 " + terceiro + "\n5 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 5 * 6, onde ficaremos com '30')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 30){
                    mask+= "como ("+n+") é menor que 30, vamos ficar com o menor número (5" + k +")";
                    mask+= "\n\n Resposta = 5"+k ;
                    Resposta.setText(mask);
                    }if(n >= 30){
                    mask+= "como ("+n+") é maior ou igual que 30, vamos ficar com o maior número (5" + terceiro +")";
                    mask+= "\n\n Resposta = 5"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 36 && n < 49){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 6, então\n repetimos o 6 antes de ambos os números, assim:\n";
                    mask+="6 " + terceiro + "\n6 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 6 * 7, onde ficaremos com '42')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 42){
                    mask+= "como ("+n+") é menor que 42, vamos ficar com o maior número (6" + k +")";
                    mask+= "\n\n Resposta = 6"+k ;
                    Resposta.setText(mask);
                    }if(n >= 42){
                    mask+= "como ("+n+") é maior ou igual que 42, vamos ficar com o maior número (6" + terceiro +")";
                    mask+= "\n\n Resposta = 6"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 49 && n < 64){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 7, então\n repetimos o 7 antes de ambos os números, assim:\n";
                    mask+="7 " + terceiro + "\n7 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 7 * 8, onde ficaremos com '56')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 56){
                    mask+= "como ("+n+") é menor que 56, vamos ficar com o menor número (7" + k +")";
                    mask+= "\n\n Resposta = 7"+k ;
                    Resposta.setText(mask);
                    }if(n >= 56){
                    mask+= "como ("+n+") é maior ou igual que 56, vamos ficar com o maior número (7" + terceiro +")";
                    mask+= "\n\n Resposta = 7"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 64 && n < 91){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 8, então\n repetimos o 8 antes de ambos os números, assim:\n";
                    mask+="8 " + terceiro + "\n8 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 8 * 9, onde ficaremos com '72')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 72){
                    mask+= "como ("+n+") é menor que 72, vamos ficar com o menor número (8" + k +")";
                    mask+= "\n\n Resposta = 8"+k ;
                    Resposta.setText(mask);
                    }if(n >= 72){
                    mask+= "como ("+n+") é maior ou igual que 72, vamos ficar com o maior número (8" + terceiro +")";
                    mask+= "\n\n Resposta = 8"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 91 && n < 100){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 9, então\n repetimos o 9 antes de ambos os números, assim:\n";
                    mask+="9 " + terceiro + "\n9 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 9 * 10, onde ficaremos com '90')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 90){
                    mask+= "como ("+n+") é menor que 90, vamos ficar com o menor número (9" + k +")";
                    mask+= "\n\n Resposta = 9"+k ;
                    Resposta.setText(mask);
                    }if(n >= 90){
                    mask+= "como ("+n+") é maior ou igual que 90, vamos ficar com o maior número (9" + terceiro +")";
                    mask+= "\n\n Resposta = 9"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
            }
            
            
            if(terceiro == 1 || terceiro == 2 || terceiro == 3){
            int k = 10 - terceiro;
                System.out.println("aaaaa " +terceiro);
                mask+= "Como no nosso caso não é,vamos achar a raiz exata mais próxima, e completar pra 10 :\n" + "1" + "\n" + k + "\n\n";
                terceiro=1;
                k=9;
                if(n >= 10 && n < 16){
                    mask+="Agora vamos, ver a raíz exata mais perto dos dpos primeiros números ("+n+"), que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                    mask+="3 " + "1" + "\n3 " + "9";
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o a raiz achada"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 12){
                    mask+= "como "+n+" é menor que 12, vamos ficar com o menor número (3" + "1" +")";
                    mask+= "\n\n Resposta = 3"+"1" ;
                    Resposta.setText(mask);}
                    if(n >=12){
                        mask+= "como "+n+" é maior ou igual a 12, vamos ficar com o maior número (3" + "9" +")";
                    mask+= "\n\n Resposta = 3"+"9" ;
                    Resposta.setText(mask);
                    }
                    }
                
                if(n >= 16 && n <= 24){
                    terceiro = 1;
                    System.out.println("aaa " + n);
                    k = 9;
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 4, então\n repetimos o 4 antes de ambos os números, assim:\n";
                    mask+="4 " + terceiro + "\n4 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 4 * 5, onde ficaremos com '20')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 20){
                    mask+= "como "+n+" é menor que 20, vamos ficar com o menor número (4" + terceiro +")";
                    mask+= "\n\n Resposta = 4"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 20){
                    mask+= "como "+n+" é maior ou igual a 20, vamos ficar com o maior número (4" + k +")";
                    mask+= "\n\n Resposta = 4"+k ;
                    Resposta.setText(mask);
                    
                    }
                }
                
                if (n >= 25 && n < 36){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 5, então\n repetimos o 5 antes de ambos os números, assim:\n";
                    mask+="5 " + terceiro + "\n5 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 5 * 6, onde ficaremos com '30')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 30){
                    mask+= "como ("+n+") é menor que 30, vamos ficar com o menor número (5" + terceiro +")";
                    mask+= "\n\n Resposta = 5"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 30){
                    mask+= "como ("+n+") é maior ou igual que 30, vamos ficar com o maior número (5" + k +")";
                    mask+= "\n\n Resposta = 5"+k ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 36 && n < 49){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 6, então\n repetimos o 6 antes de ambos os números, assim:\n";
                    mask+="6 " + terceiro + "\n6 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 6 * 7, onde ficaremos com '42')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 42){
                    mask+= "como ("+n+") é menor que 42, vamos ficar com o maior número (6" + terceiro +")";
                    mask+= "\n\n Resposta = 6"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 42){
                    mask+= "como ("+n+") é maior ou igual que 42, vamos ficar com o maior número (6" + k +")";
                    mask+= "\n\n Resposta = 6"+k ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 49 && n < 64){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 7, então\n repetimos o 7 antes de ambos os números, assim:\n";
                    mask+="7 " + terceiro + "\n7 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 7 * 8, onde ficaremos com '56')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 56){
                    mask+= "como ("+n+") é menor que 56, vamos ficar com o menor número (7" + terceiro +")";
                    mask+= "\n\n Resposta = 7"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 56){
                    mask+= "como ("+n+") é maior ou igual que 56, vamos ficar com o maior número (7" + k +")";
                    mask+= "\n\n Resposta = 7"+k ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 64 && n < 91){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 8, então\n repetimos o 8 antes de ambos os números, assim:\n";
                    mask+="8 " + terceiro + "\n8 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 8 * 9, onde ficaremos com '72')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 72){
                    mask+= "como ("+n+") é menor que 72, vamos ficar com o menor número (8" + terceiro +")";
                    mask+= "\n\n Resposta = 8"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 72){
                    mask+= "como ("+n+") é maior ou igual que 72, vamos ficar com o maior número (8" + k +")";
                    mask+= "\n\n Resposta = 8"+k ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 91 && n < 100){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 9, então\n repetimos o 9 antes de ambos os números, assim:\n";
                    mask+="9 " + terceiro + "\n9 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 9 * 10, onde ficaremos com '90')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 90){
                    mask+= "como ("+n+") é menor que 90, vamos ficar com o menor número (9" + terceiro +")";
                    mask+= "\n\n Resposta = 9"+terceiro ;
                    Resposta.setText(mask);
                    }if(n >= 90){
                    mask+= "como ("+n+") é maior ou igual que 90, vamos ficar com o maior número (9" + k +")";
                    mask+= "\n\n Resposta = 9"+k ;
                    Resposta.setText(mask);
                    }
                }
            
            }
             if(terceiro ==4 || terceiro==7 || terceiro==8){
                int k;                
                mask+= "Como no nosso caso não é,vamos achar a raiz exata mais próxima, e completar pra 10 :\n" + "2" + "\n" + "8" + "\n\n";
                terceiro=8; //inverti o K e o 8 pra não precisar inverter todas as variáveis dessa porra
                k=2;
                if(n >= 10 && n < 16){
                    mask+="Agora vamos, ver a raíz exata mais perto dos dpos primeiros números ("+n+"), que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                    mask+="3 " + terceiro + "\n3 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o a raiz achada"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 12){
                    mask+= "como "+n+" é menor que 12, vamos ficar com o menor número (3" + k+")";
                    mask+= "\n\n Resposta = 3"+k ;
                    Resposta.setText(mask);}
                    if(n >=12){
                        mask+= "como "+n+" é maior ou igual a 12, vamos ficar com o maior número (3" + terceiro +")";
                    mask+= "\n\n Resposta = 3"+terceiro ;
                    Resposta.setText(mask);
                    }
                    }
                
                if(n >= 16 && n < 25){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 4, então\n repetimos o 4 antes de ambos os números, assim:\n";
                    mask+="4 " + terceiro + "\n4 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 4 * 5, onde ficaremos com '20')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 20){
                    mask+= "como "+n+" é menor que 20, vamos ficar com o menor número (4" + k +")";
                    mask+= "\n\n Resposta = 2"+k ;
                    Resposta.setText(mask);
                    }if(n >= 20){
                    mask+= "como "+n+" é maior ou igual a 20, vamos ficar com o maior número (4" + terceiro +")";
                    mask+= "\n\n Resposta = 4"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 25 && n < 36){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 5, então\n repetimos o 5 antes de ambos os números, assim:\n";
                    mask+="5 " + terceiro + "\n5 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 5 * 6, onde ficaremos com '30')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 30){
                    mask+= "como ("+n+") é menor que 30, vamos ficar com o menor número (5" + k +")";
                    mask+= "\n\n Resposta = 5"+k ;
                    Resposta.setText(mask);
                    }if(n >= 30){
                    mask+= "como ("+n+") é maior ou igual que 30, vamos ficar com o maior número (5" + terceiro +")";
                    mask+= "\n\n Resposta = 5"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 36 && n < 49){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 6, então\n repetimos o 6 antes de ambos os números, assim:\n";
                    mask+="6 " + terceiro + "\n6 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 6 * 7, onde ficaremos com '42')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 42){
                    mask+= "como ("+n+") é menor que 42, vamos ficar com o maior número (6" + k +")";
                    mask+= "\n\n Resposta = 6"+k ;
                    Resposta.setText(mask);
                    }if(n >= 42){
                    mask+= "como ("+n+") é maior ou igual que 42, vamos ficar com o maior número (6" + terceiro +")";
                    mask+= "\n\n Resposta = 6"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 49 && n < 64){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 7, então\n repetimos o 7 antes de ambos os números, assim:\n";
                    mask+="7 " + terceiro + "\n7 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 7 * 8, onde ficaremos com '56')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 56){
                    mask+= "como ("+n+") é menor que 56, vamos ficar com o menor número (7" + k +")";
                    mask+= "\n\n Resposta = 7"+k ;
                    Resposta.setText(mask);
                    }if(n >= 56){
                    mask+= "como ("+n+") é maior ou igual que 56, vamos ficar com o maior número (7" + terceiro +")";
                    mask+= "\n\n Resposta = 7"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 64 && n < 91){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 8, então\n repetimos o 8 antes de ambos os números, assim:\n";
                    mask+="8 " + terceiro + "\n8 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 8 * 9, onde ficaremos com '72')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 72){
                    mask+= "como ("+n+") é menor que 72, vamos ficar com o menor número (8" + k +")";
                    mask+= "\n\n Resposta = 8"+k ;
                    Resposta.setText(mask);
                    }if(n >= 72){
                    mask+= "como ("+n+") é maior ou igual que 72, vamos ficar com o maior número (8" + terceiro +")";
                    mask+= "\n\n Resposta = 8"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 91 && n < 100){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 9, então\n repetimos o 9 antes de ambos os números, assim:\n";
                    mask+="9 " + terceiro + "\n9 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 9 * 10, onde ficaremos com '90')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 90){
                    mask+= "como ("+n+") é menor que 90, vamos ficar com o menor número (9" + k +")";
                    mask+= "\n\n Resposta = 9"+k ;
                    Resposta.setText(mask);
                    }if(n >= 90){
                    mask+= "como ("+n+") é maior ou igual que 90, vamos ficar com o maior número (9" + terceiro +")";
                    mask+= "\n\n Resposta = 9"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
             }
            
             
             if(terceiro == 9){
                 int k = 10 - terceiro;
                
                mask+= "Como no nosso caso não é,vamos achar a raiz exata mais próxima, e completar pra 10 :\n" + "3" + "\n" + "7" + "\n\n";
                terceiro=7; //inverti o K e o 8 pra não precisar inverter todas as variáveis dessa porra
                k=3;
                if(n >= 10 && n < 16){
                    mask+="Agora vamos, ver a raíz exata mais perto dos dpos primeiros números ("+n+"), que no nosso \ncaso é 3, então\n repetimos o 3 antes de ambos os números, assim:\n";
                    mask+="3 " + terceiro + "\n3 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar o a raiz achada"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 3 * 4, onde ficaremos com '12')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 12){
                    mask+= "como "+n+" é menor que 12, vamos ficar com o menor número (3" + k+")";
                    mask+= "\n\n Resposta = 3"+k ;
                    Resposta.setText(mask);}
                    if(n >=12){
                        mask+= "como "+n+" é maior ou igual a 12, vamos ficar com o maior número (3" + terceiro +")";
                    mask+= "\n\n Resposta = 3"+terceiro ;
                     Resposta.setText(mask);
                    }
                    }
                
                if(n >= 16 && n < 25){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 4, então\n repetimos o 4 antes de ambos os números, assim:\n";
                    mask+="4 " + terceiro + "\n4 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 4 * 5, onde ficaremos com '20')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 20){
                    mask+= "como "+n+" é menor que 20, vamos ficar com o menor número (4" + k +")";
                    mask+= "\n\n Resposta = 4"+k ;
                    Resposta.setText(mask);
                    }if(n >= 20){
                    mask+= "como "+n+" é maior ou igual a 20, vamos ficar com o maior número (4" + terceiro +")";
                    mask+= "\n\n Resposta = 4"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 25 && n < 36){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 5, então\n repetimos o 5 antes de ambos os números, assim:\n";
                    mask+="5 " + terceiro + "\n5 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 5 * 6, onde ficaremos com '30')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 30){
                    mask+= "como ("+n+") é menor que 30, vamos ficar com o menor número (5" + k +")";
                    mask+= "\n\n Resposta = 5"+k ;
                    Resposta.setText(mask);
                    }if(n >= 30){
                    mask+= "como ("+n+") é maior ou igual que 30, vamos ficar com o maior número (5" + terceiro +")";
                    mask+= "\n\n Resposta = 5"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 36 && n < 49){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 6, então\n repetimos o 6 antes de ambos os números, assim:\n";
                    mask+="6 " + terceiro + "\n6 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 6 * 7, onde ficaremos com '42')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 42){
                    mask+= "como ("+n+") é menor que 42, vamos ficar com o maior número (6" + k +")";
                    mask+= "\n\n Resposta = 6"+k ;
                    Resposta.setText(mask);
                    }if(n >= 42){
                    mask+= "como ("+n+") é maior ou igual que 42, vamos ficar com o maior número (6" + terceiro +")";
                    mask+= "\n\n Resposta = 6"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 49 && n < 64){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 7, então\n repetimos o 7 antes de ambos os números, assim:\n";
                    mask+="7 " + terceiro + "\n7 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 7 * 8, onde ficaremos com '56')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 56){
                    mask+= "como ("+n+") é menor que 56, vamos ficar com o menor número (7" + k +")";
                    mask+= "\n\n Resposta = 7"+k ;
                    Resposta.setText(mask);
                    }if(n >= 56){
                    mask+= "como ("+n+") é maior ou igual que 56, vamos ficar com o maior número (7" + terceiro +")";
                    mask+= "\n\n Resposta = 7"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 64 && n < 91){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 8, então\n repetimos o 8 antes de ambos os números, assim:\n";
                    mask+="8 " + terceiro + "\n8 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 8 * 9, onde ficaremos com '72')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 72){
                    mask+= "como ("+n+") é menor que 72, vamos ficar com o menor número (8" + k +")";
                    mask+= "\n\n Resposta = 8"+k ;
                    Resposta.setText(mask);
                    }if(n >= 72){
                    mask+= "como ("+n+") é maior ou igual que 72, vamos ficar com o maior número (8" + terceiro +")";
                    mask+= "\n\n Resposta = 8"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
                
                if (n >= 91 && n < 100){
                    mask+="Agora vamos, ver a raíz exata mais perto do primeiro número ("+n+"), que no nosso \ncaso é 9, então\n repetimos o 9 antes de ambos os números, assim:\n";
                    mask+="9 " + terceiro + "\n9 " + k;
                    mask+="\n\nNossa resposta é uma dessas duas, para descobrirmos qual delas é, é \nbem simples, basta pegar a raiz"
                            + " e multiplicar pelo seu sucessor \n(no nosso caso, 9 * 10, onde ficaremos com '90')."
                            + " Agora basta comparar o primeiro\n dígito com essa resposta. Caso o primeiro dígito for menor, você pega o menor número, caso seja maior, você pega o maior número.\n";
                    if(n < 90){
                    mask+= "como ("+n+") é menor que 90, vamos ficar com o menor número (9" + k +")";
                    mask+= "\n\n Resposta = 9"+k ;
                    Resposta.setText(mask);
                    }if(n >= 90){
                    mask+= "como ("+n+") é maior ou igual que 90, vamos ficar com o maior número (9" + terceiro +")";
                    mask+= "\n\n Resposta = 9"+terceiro ;
                    Resposta.setText(mask);
                    }
                }
             }
            
            
            
            
        }
        
        
        }
        
        
        else{
        System.out.println("é raiz cúbica mesmo mano");

        }
        }else{
        Resposta.setText("Sua raiz não é um número exato, não poderemos aproveitar\n"
                + "um método didático :c resposta: " + f);}
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Resposta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField raiz;
    private javax.swing.JComboBox<String> verifica;
    // End of variables declaration//GEN-END:variables

}
